engines:
  pylint:
    enabled: true
    config:
      max-args: 10        # Increase from default 5
      max-statements: 100  # Increase from default 50

exclude_paths:
  - docs/source/conf.py
  - lab/**
  - .github/**
  - scripts/**